version: '3'
services:
  # ECP Section
  # --- Component Directory
  directory:
    image: "entsoe/ecp-directory:${ECP_VERSION}"
    container_name: ecp-directory
    tty: true
    volumes:
      - ./directory/logs:/var/log/ecp-directory
      - ./directory/data:/var/lib/ecp-directory
      - ./directory/config:/etc/ecp-directory
    ports:
      - 10000:8080
      - 10003:8443
    environment:
      # Modify to set custom JVM arguments
      - JAVA_OPTS=-Xms64M -Xmx512M
    networks:
      edx-test-network:
        ipv4_address: 172.32.3.2
  # --- Endpoint 1 - for Catalogue
  endpoint-catalogue:
   image: "entsoe/ecp-endpoint:${ECP_VERSION}"
   container_name: ecp-endpoint-catalogue
   tty: true
   environment:
     # Modify to set custom JVM arguments
     - JAVA_OPTS=-Xms64M -Xmx512M
   volumes:
       - ./endpoint-catalogue/log:/var/log/ecp-endpoint
       - ./endpoint-catalogue/data:/var/lib/ecp-endpoint
       - ./endpoint-catalogue/config:/etc/ecp-endpoint
   ports:
       - 11000:8080
   networks:
       edx-test-network:
         ipv4_address: 172.32.3.4
  # --- Endpoint 2 - for Toolbox
  endpoint-toolbox:
   image: "entsoe/ecp-endpoint:${ECP_VERSION}"
   container_name: ecp-endpoint-toolbox
   tty: true
   environment:
     # Modify to set custom JVM arguments
     - JAVA_OPTS=-Xms64M -Xmx512M
   volumes:
       - ./endpoint-toolbox/log:/var/log/ecp-endpoint
       - ./endpoint-toolbox/data:/var/lib/ecp-endpoint
       - ./endpoint-toolbox/config:/etc/ecp-endpoint
   ports:
       - 12000:8080
   networks:
       edx-test-network:
         ipv4_address: 172.32.3.5
  # --- Broker
  broker:
     image: "entsoe/ecp-broker:${ECP_VERSION}"
     container_name: ecp-broker
     tty: true
     environment:
       # Modify to configure broker JVM memory allocation
       - ACTIVEMQ_OPTS_MEMORY=-Xms64M -Xmx512M
     volumes:
       - ./broker/config:/opt/ecp/config
       - ./broker/data:/opt/activemq/data
       - ./broker/directory:/opt/ecp/directory
     ports:
       - 13010:8161
       - 13011:5671
       - 13013:5673
     networks:
       edx-test-network:
         ipv4_address: 172.32.3.3
  # EDX Section
  # Catalogue
  catalogue:
    image: "entsoe/edx-catalogue:${EDX_VERSION}"
    container_name: edx-catalogue
    tty: true
    volumes:
      - ./catalogue/logs:/var/log/edx-catalogue
      - ./catalogue/data:/var/lib/edx-catalogue
      - ./catalogue/config:/etc/edx-catalogue
    ports:
      - 14000:8080
    environment:
      # Modify to set custom JVM arguments
      - JAVA_OPTS=-Xms64M -Xmx512M
    networks:
      edx-test-network:
        ipv4_address: 172.32.3.10
  # Toolbox
  toolbox:
    image: "entsoe/edx-toolbox:${EDX_VERSION}"
    container_name: edx-toolbox
    tty: true
    volumes:
      - ./toolbox/logs:/var/log/edx-toolbox
      - ./toolbox/data:/var/lib/edx-toolbox
      - ./toolbox/config:/etc/edx-toolbox
    ports:
      - 15000:8080
    environment:
      # Modify to set custom JVM arguments
      - JAVA_OPTS=-Xms64M -Xmx512M
    networks:
      edx-test-network:
        ipv4_address: 172.32.3.11
networks:
  edx-test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.3.0/24
