# Author: Stanislav Novotny

# Run
# docker-compose up -d

# Test
# docker-compose ps
# http://localhost:8161/

version: '3'

services:
 broker:
  container_name: mybroker
  image: novst/apache-activemq
  ports:
   - "8161:8161"

 producer:
  image: novst/amqpproducer
  command: --amqpUrl=tcp://broker:61616
  restart: on-failure

 consumer:
  depends_on:
    - broker
  image: novst/amqpconsumer
  command: --amqpUrl=tcp://broker:61616
  restart: on-failure
