# Author: Stanislav Novotny

# Run
# docker-compose up -d

# Test
# docker-compose ps
# http://localhost:8161/

version: '3'

services:
 broker:
  image: novst/apache-activemq
  ports:
   - "8161:8161"
  networks:
   dcn:
    ipv4_address: 10.10.10.2
 producer:
  image: novst/amqpproducer
  command: --amqpUrl=tcp://10.10.10.2:61616
  networks:
   dcn:
    ipv4_address: 10.10.10.3
    
networks:
 dcn:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 10.10.10.0/24