Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.ssh.insert_key = false

  config.vm.define "swarmnode1" do |swarmnode1|
    swarmnode1.vm.hostname = "swarmnode1"
    swarmnode1.vm.network "private_network", ip: "10.20.30.4"
    swarmnode1.vm.provider "virtualbox" do |v|
      v.memory = "2048"
      v.cpus = "2"
    end
  end

  config.vm.define "swarmnode2" do |swarmnode2|
    swarmnode2.vm.hostname = "swarmnode2"
    swarmnode2.vm.network "private_network", ip: "10.20.30.5"
    swarmnode2.vm.provider "virtualbox" do |v|
      v.memory = "2048"
      v.cpus = "2"
    end
  end

  config.vm.define "swarmnode3" do |swarmnode3|
    swarmnode3.vm.hostname = "swarmnode3"
    swarmnode3.vm.network "private_network", ip: "10.20.30.6"
    swarmnode3.vm.provider "virtualbox" do |v|
      v.memory = "2048"
      v.cpus = "2"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
   sudo yum remove -y docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine
    sudo yum install -y yum-utils \
      device-mapper-persistent-data \
      lvm2
    sudo yum-config-manager \
      --add-repo \
      https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install -y docker-ce docker-ce-cli containerd.io
    firewall-cmd --add-port=2376/tcp --permanent
    firewall-cmd --add-port=2377/tcp --permanent
    firewall-cmd --add-port=7946/tcp --permanent
    firewall-cmd --add-port=7946/udp --permanent
    firewall-cmd --add-port=4789/udp --permanent
    firewall-cmd --reload
    sudo systemctl start docker
    sudo systemctl enable docker
 SHELL

end
